### PR TITLE
Oauth stuff

### PR DESCRIPTION
**Pull request by Andihedral**

### CODE REVIEW

**Comment by Yey007** [comment]
This is sort of done but I don't want to merge it until we test it with a login page

**Comment by Yey007** [comment]
Ok so this Oauth works (adds to userlist) but we will have to obtain some tokens. I just tested with some temporary ones. Good work, @Andihedral .

**Comment by Yey007** [comment]
Feel free to move this out of draft stage if you feel it's ready

**Comment by Yey007** [comment]
@ecukier @Andihedral I merged the oauth stuff with the new frontend, take a look if you can.

**Review by ecukier — APPROVED** [review]

**Pull request merged**
